#!/bin/bash
DISPLAY=:0.0

function get_setimage
{
    magic=72
    let RAND=${RANDOM}%${magic}
    TODAY=$(date "+%Y%m%d")
    CACHE=/tmp/bingwp_list_${TODAY}
    if [[ ! -s  ${CACHE} ]]
    then curl -sL \
        "http://www.bing.com/gallery/home/browsedata?z=0" \
	| sed "s/.*browseData=\({[^}]*}\).*/\1/" \
	| jq .imageNames |sed 1d |head -n ${magic} \
	| tr -d "\"" | tr -d "," \
	> ${CACHE}
    fi
    IMAGE_LIST=($(cat ${CACHE}))
    URL=http://cn.bing.com/az/hprichbg/rb/${IMAGE_LIST[$RAND]}_1920x1080.jpg
    STATUS_CODE=$(curl -sL ${URL} -o /tmp/.tmp.bg.$(whoami).jpg -w %{http_code})
    if [ ${STATUS_CODE} == "200" ]
        then rm -f /tmp/bg.$(whoami).jpg \
	    && mv /tmp/.tmp.bg.$(whoami).jpg /tmp/bg.$(whoami).jpg \
            && pcmanfm --display :0.0 -w /tmp/bg.$(whoami).jpg \
	    && return 0
        else
	    return 1
    fi
}

function main
{
    COUNT=0
    while true
        do 
            get_setimage
            RET=$?
	    let COUNT=$COUNT+1
            if [[ $RET -eq 0 || $COUNT -eq 10 ]]
                then exit $RET
            fi
        done
}

main
